const {chromium}=require(process.env.PW || 'playwright');
const OUT=process.argv[2];
(async()=>{
  const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1440,height:900}});
  const errs=[]; p.on('pageerror',e=>errs.push('PAGE '+e.message)); p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
  await p.goto('http://localhost:8765/'); await p.evaluate(()=>localStorage.clear()); await p.reload(); await p.waitForTimeout(500);
  const as=async who=>{ await p.click('.who'); await p.click(`.menu-item:has-text("${who}")`); await p.waitForTimeout(250); };
  const btn=async t=>{ await p.click(`.modal button:has-text("${t}")`); await p.waitForTimeout(350); };
  const col=async title=>p.evaluate(t=>{const c=[...document.querySelectorAll('[data-card]')].find(x=>x.querySelector('.c-title').textContent===t); return c? c.closest('.col').querySelector('.col-n').textContent+' | '+(c.querySelector('.c-turn')||c.querySelector('.c-meta'))?.textContent : 'нет';},title);
  const open=async t=>{ await p.click(`[data-card]:has(.c-title:text-is("${t}"))`); await p.waitForTimeout(450); };
  const close=async()=>{ await p.click('.modal [aria-label="Закрыть"]'); await p.waitForTimeout(450); };
  const T='Режиссёр монтажа';
  await as('Данияр');
  const sel=async(k,t)=>{ await p.click(`.modal [data-k=${k}]`); await p.click(`.pop .opt:has-text("${t}")`); await p.waitForTimeout(150); };
  const task=async(t,b)=>{ await p.click(`.task:has-text("${t}") button:has-text("${b}")`); await p.waitForTimeout(400); };
  await p.click('button:has-text("Создать заявку")'); await p.waitForTimeout(500);
  await btn('Далее');
  const errsShown=await p.$$eval('.modal .err',e=>e.map(x=>x.textContent)); console.log('step1 errors:',errsShown.length, errsShown.slice(0,3).join('; '));
  await p.screenshot({path:OUT+'/f-form-err.png'});
  await p.fill('[data-k=title]',T); await p.fill('[data-k=project]','Project X');
  await p.check('input[name=reason] >> nth=0'); await btn('Далее');
  await p.fill('[data-k=duties]','Сборка рекламных роликов от черновой сборки до мастера.');
  await p.fill('[data-k=reqs]','Портфолио, Premiere Pro.'); await p.fill('[data-k=experience]','От 3 лет'); await btn('Далее');
  await p.fill('[data-k=salary]','600000abc'); console.log('salary field:', await p.inputValue('[data-k=salary]'));
  await p.click('[data-k=start]'); await p.click('.pop.cal [aria-label="Следующий месяц"]'); await p.click('.pop.cal .cal-d:not([disabled]) >> nth=3'); await p.waitForTimeout(150);
  console.log('start:', await p.textContent('[data-k=start]'));
  await btn('Далее'); await btn('Отправить в HR'); await p.waitForTimeout(400);
  console.log('after send:', await col(T), '| hash', await p.evaluate(()=>location.hash));
  await close();
  await as('Гульнара');
  await open(T); await btn('На доработку'); await btn('Вернуть на доработку');
  console.log('empty return err:', await p.$eval('.modal .err',e=>e.textContent).catch(()=>'нет'));
  await p.click('.modal .rev:has(dt:has-text("Бонусы")) .rev-b'); await p.fill('.modal .rev-t','Добавьте бонусную часть.');
  await p.screenshot({path:OUT+'/f-review.png'});
  await btn('Вернуть на доработку');
  console.log('returned:', await col(T)); await close();
  await as('Данияр'); await open(T);
  console.log('note at field:', await p.$eval('.modal .has-note .fnote',e=>e.textContent).catch(()=>'нет'));
  await p.screenshot({path:OUT+'/f-returned.png'});
  await p.fill('[data-k=bonus]','10% от бюджета проекта'); await btn('Отправить снова'); await close();
  console.log('resent:', await col(T));
  await as('Гульнара'); await open(T); await btn('Принять'); await close();
  await as('Ринат'); await p.screenshot({path:OUT+'/f-fin.png'}); await task(T,'Согласовать');
  await as('Арман'); await task(T,'Одобрить');
  await as('Данияр'); console.log('approved:', await col(T));
  await as('Гульнара'); await open(T); await sel('rec','Самат'); await btn('Назначить'); await close();
  await as('Самат'); await open(T); await btn('Опубликовано'); 
  console.log('published:', await col(T));
  await btn('Добавить кандидата'); await btn('Добавить');
  console.log('cand errs:', await p.$$eval('.modal .err',e=>e.map(x=>x.textContent).join('; ')));
  await p.fill('#ac-name','Олжас Тулеуов'); await p.fill('#ac-phone','+7 701 555 12 34'); await p.click('#ac-source'); await p.click('.pop .opt:has-text("HH")');
  await btn('Добавить');
  await btn('Руководителю на решение');
  await p.screenshot({path:OUT+'/f-cand.png'});
  await close();
  await as('Данияр'); console.log('mgr turn:', await col(T)); await open(T);
  await btn('Одобрить кандидата'); await p.click('.modal .decide button:text-is("Одобрить")'); await p.waitForTimeout(350); await close();
  await as('Самат'); await open(T); await p.click('.modal .cc-n:has-text("Олжас")'); await p.waitForTimeout(400); await p.screenshot({path:OUT+'/f-cand-doc.png'});
  await btn('Оффер отправлен'); await btn('Согласился'); await close();
  console.log('accepted:', await col(T));
  await open(T);
  await p.click('.modal .ck >> nth=0'); console.log('one ticked:', await p.textContent('.modal .clg-n'));
  { while(await p.locator('.modal .clg button:has-text("Отметить все")').count()){ await p.locator('.modal .clg button:has-text("Отметить все")').first().click(); await p.waitForTimeout(150); } }
  await p.screenshot({path:OUT+'/f-prep.png'});
  await btn('Вышел на стажировку'); await close();
  console.log('intern:', await col(T));
  await as('Данияр'); await open(T); await btn('Сохранить решение');
  console.log('dec errs:', await p.$$eval('.modal .err',e=>e.map(x=>x.textContent).join('; ')));
  await p.click('.modal .seg button:has-text("Нанимаем")'); await p.fill('.modal textarea','Берём.'); await btn('Сохранить решение'); await close();
  console.log('docs:', await col(T));
  await as('Самат'); await open(T);
  { while(await p.locator('.modal .clg button:has-text("Отметить все")').count()){ await p.locator('.modal .clg button:has-text("Отметить все")').first().click(); await p.waitForTimeout(150); } }
  await btn('Сотрудник оформлен'); await close();
  await as('Ринат'); await task('Олжас Тулеуов','Учесть в ФОТ');
  await as('Самат'); console.log('recruiter cols:', await p.$$eval('.col-n',e=>e.map(x=>x.textContent).join(', ')));
  await as('Гульнара'); console.log('final:', await col(T));
  await open(T); await p.click('.tl-more').catch(()=>{}); await p.waitForTimeout(200); await p.screenshot({path:OUT+'/f-path.png', fullPage:false});
  console.log(errs.join('\n')||'no errors');
  await b.close();
})();
