const {chromium}=require(process.env.PW || 'playwright');
const OUT=process.argv[2];
(async()=>{
  const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1440,height:900}});
  const errs=[]; p.on('pageerror',e=>errs.push('PAGE '+e.message)); p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
  await p.goto('http://localhost:8765/'); await p.evaluate(()=>localStorage.clear()); await p.reload(); await p.waitForTimeout(500);
  const as=async who=>{ await p.click('.who'); await p.click(`.menu-item:has-text("${who}")`); await p.waitForTimeout(250); };
  const btn=async t=>{ await p.click(`.modal button:has-text("${t}")`); await p.waitForTimeout(350); };
  const col=async title=>p.evaluate(t=>{const c=[...document.querySelectorAll('[data-card]')].find(x=>x.querySelector('.c-title').textContent===t); return c? c.closest('.col').querySelector('.col-n').textContent+' | '+(c.querySelector('.c-turn')||c.querySelector('.c-meta'))?.textContent : 'нет';},title);
  const open=async t=>{ await p.click(`[data-card]:has(.c-title:text-is("${t}"))`); await p.waitForTimeout(450); };
  const close=async()=>{ await p.click('.modal [aria-label="Закрыть"]'); await p.waitForTimeout(450); };
  const T='Режиссёр монтажа';
  await as('Данияр');
  await p.click('button:has-text("Создать заявку")'); await p.waitForTimeout(500);
  await btn('Отправить в HR');
  const errsShown=await p.$$eval('.modal .err',e=>e.map(x=>x.textContent)); console.log('validation:',errsShown.length, errsShown.slice(0,3).join('; '));
  await p.screenshot({path:OUT+'/f-form-err.png'});
  await p.fill('[data-k=title]',T); await p.fill('[data-k=project]','Project X');
  await p.check('input[name=reason] >> nth=0');
  await p.fill('[data-k=duties]','Сборка рекламных роликов от черновой сборки до мастера.');
  await p.fill('[data-k=reqs]','Портфолио, Premiere Pro.'); await p.fill('[data-k=experience]','От 3 лет');
  await p.fill('[data-k=salary]','600 000 ₸'); await p.fill('[data-k=start]','2026-11-02');
  await btn('Отправить в HR'); await p.waitForTimeout(400);
  console.log('after send:', await col(T), '| hash', await p.evaluate(()=>location.hash));
  await close();
  await as('Гульнара');
  await open(T); await btn('На доработку'); await btn('Вернуть на доработку');
  console.log('empty comment err:', await p.$eval('.modal .err',e=>e.textContent).catch(()=>'нет'));
  await p.fill('.modal textarea','Добавьте бонусную часть.'); await btn('Вернуть на доработку');
  console.log('returned:', await col(T)); await close();
  await as('Данияр'); await open(T); await btn('Доработать');
  await p.fill('[data-k=salary]','600 000 ₸ + бонус'); await btn('Отправить снова'); await close();
  console.log('resent:', await col(T));
  await as('Гульнара'); await open(T); await btn('Принять'); await close();
  await as('Ринат'); await open(T); await p.screenshot({path:OUT+'/f-fin.png'}); await btn('Согласовать'); await close();
  await as('Арман'); await open(T); await btn('Одобрить'); await close();
  console.log('approved:', await col(T));
  await as('Гульнара'); await open(T); await p.selectOption('.modal select[data-k=rec]', 'sam'); await btn('Назначить'); await close();
  await as('Самат'); await open(T); await btn('Взять в работу'); await btn('Опубликовано'); 
  console.log('published:', await col(T));
  await btn('Добавить кандидата'); await btn('Добавить');
  console.log('cand errs:', await p.$$eval('.modal .err',e=>e.map(x=>x.textContent).join('; ')));
  await p.fill('#ac-name','Олжас Тулеуов'); await p.fill('#ac-phone','+7 701 555 12 34'); await p.selectOption('#ac-source','HH');
  await btn('Добавить');
  await btn('Пригласить на интервью'); await btn('Пригласить'); await btn('Передать руководителю');
  await p.screenshot({path:OUT+'/f-cand.png'});
  await close();
  await as('Данияр'); console.log('mgr turn:', await col(T)); await open(T);
  await btn('Одобрить'); await btn('Одобрить кандидата'); await close();
  await as('Самат'); await open(T); await p.click('.modal .cc-n:has-text("Олжас")'); await p.waitForTimeout(400);
  await btn('Отправить оффер'); await btn('Согласился'); await close();
  console.log('accepted:', await col(T));
  await open(T);
  for(const who of ['Самат']){ const boxes=await p.locator('.modal .ck input:not([disabled])').elementHandles(); for(const bx of boxes){ if(!(await bx.isChecked())) await bx.check(); } }
  await close(); await as('Олжас'); await open(T);
  { const boxes=await p.locator('.modal .ck input:not([disabled])').elementHandles(); for(const bx of boxes){ if(!(await bx.isChecked())) await bx.check(); } }
  await close(); await as('Самат'); await open(T); await p.screenshot({path:OUT+'/f-prep.png'});
  await btn('Вышел на стажировку'); await close();
  console.log('intern:', await col(T));
  await as('Данияр'); await open(T); await btn('Сохранить решение');
  console.log('dec errs:', await p.$$eval('.modal .err',e=>e.map(x=>x.textContent).join('; ')));
  await p.click('.modal .seg button:has-text("Нанимаем")'); await p.fill('.modal textarea','Берём.'); await btn('Сохранить решение'); await close();
  console.log('docs:', await col(T));
  await as('Самат'); await open(T);
  { const boxes=await p.locator('.modal .ck input:not([disabled])').elementHandles(); for(const bx of boxes){ if(!(await bx.isChecked())) await bx.check(); } }
  await btn('Сотрудник оформлен'); await close();
  await as('Ринат'); console.log('fin:', await col(T)); await open(T); await btn('Принято в работу'); await btn('Учтено в ФОТ'); await btn('Учтено в ФОТ'); await close();
  console.log('final:', await col(T));
  await open(T); await p.click('.tl-more').catch(()=>{}); await p.waitForTimeout(200); await p.screenshot({path:OUT+'/f-path.png', fullPage:false});
  console.log(errs.join('\n')||'no errors');
  await b.close();
})();
